### ISSUE TITLE
iyi günler arda bey yeni kitabınızı aldım 

### ISSUE THREAD

**Issue by delitazz** [Ardakilic/raspberry-pi-kitap#4]
fotoda pi store a  log in yaptıgımda paypal a yönlendiriyor diyor ama yönlendirme olmuyor veya altında bi tuş cıkmıyor ne yapabilirim.
![imag0832](https://cloud.githubusercontent.com/assets/14964673/10268320/8ce4c30c-6abd-11e5-9e23-9732822a9933.jpg)

**Comment by Ardakilic** [comment]
Merhaba, Program indirmek için login olmanıza gerek yok.

Bu sorun eskiden de vardı ve de paket güncellemesi ile çözülüyordu.

Örnek olarak yabancı forumlarda şurada da tartışılmıştı: https://www.raspberrypi.org/forums/viewtopic.php?f=83&t=68681

Önce en güncel raspbian'ı edinmiş olduğunuzdan emin olun. Eğer Raspbian sürümünüz eski ise güncelini indirin derim yol yakınken.

Ardından terminalden şu komutları çalıştırın:

``` shell
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

Sorun hala devam ederse yeniden yazarsanız beraber daha detaylı inceleyebiliriz.

**Comment by Ardakilic** [comment]
Sorunu 3 haftadır geri dönüş olmadığı için kapatıyorum. 

Ayrıca Raspbian yeni sürümlerinde artık PiStore yok, çok hatalı olduğu için sistemden kaldırıldı.

Eğer başka bir sorunuz varsa yine buradan issue açabilirsiniz.
